let mainBody = document.querySelector("body");
let slideMenuButton = document.querySelector("#slidemenu");
let slideMenuText = document.querySelector("#slidemenuText");
let operatorMenu = document.querySelector("#operator");
let homePage = document.querySelector("#homepage");
let calcPage = document.querySelector("#contactspage");
let accessoriesPage = document.querySelector("#accessoriespage");
let invoicePage = document.querySelector("#invoicepage");
let materialsPage = document.querySelector("#quotepage");
let materialsCard = document.querySelector("#quotecard");
let accessoriesCard = document.querySelector("#accessoriesCard");
let contactsCard = document.querySelector("#contactsCard");
let invoiceCard = document.querySelector("#invoiceCard");
let homeButton = document.querySelector(".backhome");
let root = document.querySelector("#root");
let placeHolderDiv = document.querySelector(".placeholder");
let menuClosedButton = document.querySelector("#mclosedbtn");
let menuOpenButton = document.querySelector("#mopenbtn");
let winWidth = window.innerWidth;
let isOperatorOpen;
let windowMode;